### PR TITLE
Scrapy 2.11.1 and scrapinghub-entrypoint-scrapy 0.17.2

### PR DESCRIPTION
**Pull request by Gallaecio**

### CODE REVIEW

**Review by kmike — APPROVED** [review]

**Comment by wRAR** [comment]
No other version changes in requirements.txt? Did you regenerate it?

**Comment by Gallaecio** [comment]
I updated it with `pip-compile`, but I did not remove the `.txt` first to get the latest versions of everything, I assume we only do that with stack version changes.

**Review by wRAR — APPROVED** [review]

**Comment by elacuesta** [comment]
I've been regenerating the requirements file for every change, whether it's a patch or minor update. Also in this case, we might want to update Twisted from [22.10](https://github.com/scrapinghub/scrapinghub-stack-scrapy/blob/b6e44bfd2d60cb812291a0d9046db0415dd825b5/requirements.txt#L274) to a more recent version now that [Scrapy 2.11.1](https://github.com/scrapy/scrapy/releases/tag/2.11.1) supports it.

**Comment by Gallaecio** [comment]
Feels risky to me, but will do.

**Review by kmike — APPROVED** [review]
Looks good, but probably it'd be better to run the upgrade one more time (e.g. scrapy-zyte-smartproxy got a new release)

**Pull request closed without merging**
